crm/views/main.py
from flask import Blueprint, render_template
from crm.models import User, Order, Store, Item, OrderItem

bp = Blueprint("main", __name__, url_prefix="/")


@bp.route("/")
def index():

    user_count = User.query.count()
    order_count = Order.query.count()
    store_count = Store.query.count()
    item_count = Item.query.count()
    orderitem_count = OrderItem.query.count()

    return render_template(
        "main/index.jinja2",
        user_count=user_count,
        store_count=store_count,
        item_count=item_count,
        order_count=order_count,
        orderitem_count=orderitem_count,
    )

crm/views/orderitem.py
from flask import Blueprint, render_template, request, url_for, flash
from sqlalchemy import func
from crm.models import User, Order, Store, Item, OrderItem

bp = Blueprint("orderitem", __name__, url_prefix="/orderitem")


@bp.route("/")
def get_orderitems():
    page = request.args.get("page", 1, type=int)
    per_page = request.args.get("per_page", 10, type=int)

    if page < 1 or per_page * (page - 1) > OrderItem.query.count():
        flash("페이지 번호가 잘못되었습니다. 첫 페이지로 이동합니다.", "danger")
        page = 1

    orderitem_list = OrderItem.query.paginate(page=page, per_page=per_page)
    orderitem_total = OrderItem.query.count()

    return render_template(
        "orderitem/orderitem_list.jinja2",
        title="전체 주문 내역",
        orderitem_list=orderitem_list,
        orderitem_total=orderitem_total,
    )

crm/templates/main/index.jinja2
{% extends 'base.jinja2' %}
{% block content %}
<h1>CRM Project: Seokin Yoon</h1>
<p>CRM Project Main Page</p>

<div class="card my-3">
    <div class="card-header">주요 기능</div>
    <ul class="list-group list-group-flush">
        <a href="{{ url_for('user.get_users') }}"
            class="list-group-item list-group-item-action d-flex justify-content-between align-items-start"
            aria-current="true">
            <div class="ms-2 me-auto">
                <div>
                    <span class="text-primary fw-bold">사용자</span> 목록 조회 <span>(사용자 등록 수: {{ '{:,.0f}'.format(user_count)
                        }})</span>
                </div>
            </div>
        </a>
        <a href="{{ url_for('store.get_stores') }}"
            class="list-group-item list-group-item-action d-flex justify-content-between align-items-start"
            aria-current="true">
            <div class="ms-2 me-auto">
                <div>
                    <span class="text-primary fw-bold">매장</span> 목록 조회 <span>(매장 등록 수: {{ '{:,.0f}'.format(store_count)
                        }})</span>
                </div>
            </div>
        </a>
        <a href="{{ url_for('item.get_items') }}"
            class="list-group-item list-group-item-action d-flex justify-content-between align-items-start"
            aria-current="true">
            <div class="ms-2 me-auto">
                <div>
                    <span class="text-primary fw-bold">상품</span> 목록 조회 <span>(상품 등록 수: {{ '{:,.0f}'.format(item_count)
                        }})</span>
                </div>
            </div>
        </a>
        <a href="{{ url_for('order.get_orders') }}"
            class="list-group-item list-group-item-action d-flex justify-content-between align-items-start"
            aria-current="true">
            <div class="ms-2 me-auto">
                <div>
                    <span class="text-primary fw-bold">주문</span> 목록 조회 <span>(주문 등록 수: {{ '{:,.0f}'.format(order_count)
                        }})</span>
                </div>
            </div>
        </a>
        <a href="{{ url_for('orderitem.get_orderitems') }}"
            class="list-group-item list-group-item-action d-flex justify-content-between align-items-start"
            aria-current="true">
            <div class="ms-2 me-auto">
                <div>
                    <span class="text-primary fw-bold">전체 주문</span> 목록 조회 <span>(전체 주문 등록 수: {{
                        '{:,.0f}'.format(orderitem_count)
                        }})</span>
                </div>
            </div>
        </a>
    </ul>
</div>
<div class="card my-3">
    <div class="card-header">Database Diagram</div>
    <img src="{{ url_for('static', filename='SeSAC.CRM.png') }}" class="card-img">
</div>
{% endblock %}