crm/views/item.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from sqlalchemy import func
from crm.models import User, Order, Store, Item, OrderItem

bp = Blueprint("item", __name__, url_prefix="/item")


@bp.route("/")
def get_items():
    page = request.args.get("page", 1, type=int)
    per_page = request.args.get("per_page", 10, type=int)

    if page < 1 or per_page * (page - 1) > Item.query.count():
        flash("페이지 번호가 잘못되었습니다. 첫 페이지로 이동합니다.", "danger")
        page = 1

    item_list = Item.query.paginate(page=page, per_page=per_page)
    item_total = Item.query.count()

    name = request.args.get("name")

    if name:
        item_list = Item.query.filter(Item.Name.like(f"%{name}%")).paginate(
            page=page, per_page=per_page
        )
        item_total = Item.query.filter(Item.Name.like(f"%{name}%")).count()

        if item_total == 0:
            flash("해당 이름의 상품이 존재하지 않습니다.", "danger")
            return redirect(url_for("item.get_items"))

    return render_template(
        "item/item_list.jinja2",
        title="전체 상품 목록",
        item_list=item_list,
        item_total=item_total,
        name=name,
    )


@bp.route("/<id>")
def get_item(id):
    try:
        item = Item.query.get(id)

        if not item:
            flash("해당 상품이 존재하지 않습니다.", "danger")
            return redirect(url_for("item.get_items"))

        # ! 월간 매출액 가져오기
        # ? 1. Order 테이블과 OrderItem 테이블을 조인하여 Item 테이블의 UnitPrice를 가져온다.
        # ? 2. Order 테이블의 OrderAt 컬럼을 기준으로 월간 매출액과 주문수 리스트를 가져온다.

        sales = (
            Order.query.join(OrderItem, Order.Id == OrderItem.OrderId)
            .join(Item, OrderItem.ItemId == Item.Id)
            .add_columns(
                func.strftime("%Y년 %m월", Order.OrderAt).label("Month"),
                func.sum(Item.UnitPrice).label("MonthlySales"),
                func.count(OrderItem.Id).label("OrderCount"),
            )
            .filter(OrderItem.ItemId == id)
            .group_by("Month")
            .order_by(Order.OrderAt.desc())
            .all()
        )

        # 월간 매출액 그래프
        chart_month = []
        for sale in sales:
            chart_month.append(sale.Month)

        chart_sales = []
        for sale in sales:
            chart_sales.append(sale.MonthlySales)

        chart_sales_count = []
        for sale in sales:
            chart_sales_count.append(sale.OrderCount)

        return render_template(
            "item/item_detail.jinja2",
            title="상품 상세 정보",
            item=item,
            sales=sales,
            chart_month=chart_month,
            chart_sales=chart_sales,
            chart_sales_count=chart_sales_count,
        )
    except:
        flash("상품 정보를 가져오는 중 오류가 발생했습니다.", "danger")
        return redirect(url_for("item.get_items"))

crm/views/store.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from sqlalchemy import func

from crm.models import User, Order, Store, Item, OrderItem

bp = Blueprint("store", __name__, url_prefix="/store")


@bp.route("/")
def get_stores():
    page = request.args.get("page", 1, type=int)
    per_page = request.args.get("per_page", 10, type=int)

    if page < 1 or per_page * (page - 1) > Store.query.count():
        flash("페이지 번호가 잘못되었습니다. 첫 페이지로 이동합니다.", "danger")
        page = 1

    store_list = Store.query.paginate(page=page, per_page=per_page)
    store_total = Store.query.count()

    name = request.args.get("name")

    if name:
        store_list = Store.query.filter(Store.Name.like(f"%{name}%")).paginate(
            page=page, per_page=per_page
        )
        store_total = Store.query.filter(Store.Name.like(f"%{name}%")).count()

        if store_total == 0:
            flash("해당 이름의 상점이 존재하지 않습니다.", "danger")
            return redirect(url_for("store.get_stores"))

    return render_template(
        "store/store_list.jinja2",
        title="전체 상점 목록",
        store_list=store_list,
        store_total=store_total,
        name=name,
    )


@bp.route("/<id>")
def get_store(id):
    try:
        store = Store.query.get(id)

        if not store:
            flash("해당 상점이 존재하지 않습니다.", "danger")
            return redirect(url_for("store.get_stores"))

        # ! 월간 매출액 가져오기
        # ? 1. Order 테이블과 OrderItem 테이블을 조인하여 Item 테이블의 UnitPrice를 가져온다.
        # ? 2. 이를 Order 테이블의 OrderAt 컬럼을 기준으로 월간 매출액과 주문수 리스트를 가져온다.

        sales = (
            Order.query.join(OrderItem, Order.Id == OrderItem.OrderId)
            .join(Item, OrderItem.ItemId == Item.Id)
            .add_columns(
                func.strftime("%Y년 %m월", Order.OrderAt).label("Month"),
                func.sum(Item.UnitPrice).label("MonthlySales"),
                func.count(OrderItem.Id).label("OrderCount"),
            )
            .filter(Order.StoreId == id)
            .group_by("Month")
            .order_by(Order.OrderAt.desc())
            .all()
        )

        total_sales = sum([sale.MonthlySales for sale in sales])

        # ! 월간 매출액 그래프
        chart_month = []
        for sale in sales:
            chart_month.append(sale.Month)

        chart_sales = []
        for sale in sales:
            chart_sales.append(sale.MonthlySales)

        chart_sales_count = []
        for sale in sales:
            chart_sales_count.append(sale.OrderCount)

        # ! 단골 고객 가져오기

        vip_users = (
            User.query.join(Order, User.Id == Order.UserId)
            .add_columns(User.Name, func.count(Order.Id).label("OrderCount"))
            .filter(Order.StoreId == id)
            .group_by(User.Id)
            .order_by(func.count(Order.Id).desc())
            .limit(5)
            .all()
        )

        return render_template(
            "store/store_detail.jinja2",
            title="상점 상세 정보",
            store=store,
            sales=sales,
            total_sales=total_sales,
            vip_users=vip_users,
            chart_month=chart_month,
            chart_sales=chart_sales,
            chart_sales_count=chart_sales_count,
        )
    except:
        flash("상점 정보를 가져오는 중 오류가 발생했습니다.", "danger")
        return redirect(url_for("store.get_stores"))

crm/views/user.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from sqlalchemy import func
from crm.models import User, Order, Store, Item, OrderItem

bp = Blueprint("user", __name__, url_prefix="/user")


@bp.route("/")
def get_users():
    page = request.args.get("page", 1, type=int)
    per_page = request.args.get("per_page", 10, type=int)

    if page < 1 or per_page * (page - 1) > User.query.count():
        flash("페이지 번호가 잘못되었습니다. 첫 페이지로 이동합니다.", "danger")
        page = 1

    name = request.args.get("name")
    gender = request.args.get("gender")
    age = request.args.get("age")

    user_list = User.query.paginate(page=page, per_page=per_page)
    user_total = User.query.count()

    if name:
        user_list = User.query.filter(User.Name.like(f"%{name}%")).paginate(
            page=page, per_page=per_page
        )
        user_total = User.query.filter(User.Name.like(f"%{name}%")).count()
        if user_total == 0:
            flash("해당 이름의 회원이 존재하지 않습니다.", "danger")
            return redirect(url_for("user.get_users"))

    if gender:
        user_list = User.query.filter(User.Gender == gender).paginate(
            page=page, per_page=per_page
        )
        user_total = User.query.filter(User.Gender == gender).count()
        if user_total == 0:
            flash("해당 성별의 회원이 존재하지 않습니다.", "danger")
            return redirect(url_for("user.get_users"))

    if age:
        user_list = User.query.filter(User.Age == age).paginate(
            page=page, per_page=per_page
        )
        user_total = User.query.filter(User.Age == age).count()
        if user_total == 0:
            flash("해당 나이의 회원이 존재하지 않습니다.", "danger")
            return redirect(url_for("user.get_users"))

    return render_template(
        "user/user_list.jinja2",
        title="전체 회원 목록",
        user_list=user_list,
        user_total=user_total,
        name=name,
        gender=gender,
        age=age,
    )


@bp.route("/<id>")
def get_user(id):
    try:
        user = User.query.get(id)

        if not user:
            flash("해당 회원이 존재하지 않습니다.", "danger")
            return redirect(url_for("user.get_users"))

        # 주문 내역

        order_list = (
            Store.query.join(Order, Store.Id == Order.StoreId)
            .add_columns(Store.Name, Store.Type, Order.OrderAt)
            .filter(Order.UserId == id)
            .order_by(Order.OrderAt.desc())
            .all()
        )

        # store_top5 = (
        #     Store.query.join(Order, Store.Id == Order.StoreId)
        #     .add_columns(Store.Name, Store.Type)
        #     .filter(Order.UserId == id)
        #     .group_by(Store.Id)
        #     .order_by(func.count().desc())
        #     .limit(5)
        # )

        # visited_count = (
        #     Order.query.filter(Order.UserId == id)
        #     .add_columns(Order.StoreId, func.count())
        #     .group_by(Order.StoreId)
        #     .order_by(func.count().desc())
        #     .all()
        # )

        # 자주 방문한 매장 TOP5

        store_top5_visit = (
            Store.query.join(Order, Store.Id == Order.StoreId)
            .filter(Order.UserId == id)
            .add_columns(
                Store.Name, Store.Type, func.count(Order.StoreId).label("visit_count")
            )
            .group_by(Store.Id)
            .order_by(func.count(Order.StoreId).desc())
            .limit(5)
            .all()
        )

        # 자주 주문한 상품 TOP5

        item_top5 = (
            Item.query.join(OrderItem, Item.Id == OrderItem.ItemId)
            .join(Order, Order.Id == OrderItem.OrderId)
            .filter(Order.UserId == id)
            .add_columns(
                Item.Name, Item.Type, func.count(OrderItem.ItemId).label("order_count")
            )
            .group_by(Item.Id)
            .order_by(func.count(OrderItem.ItemId).desc())
            .limit(5)
            .all()
        )

        return render_template(
            "user/user_detail.jinja2",
            title=f"{user.Name}님의 회원 정보",
            user=user,
            order_list=order_list,
            store_top5=store_top5_visit,
            item_top5=item_top5,
        )
    except:
        flash("사용자 정보를 가져오는 중 오류가 발생했습니다.", "danger")
        return redirect(url_for("user.get_users"))

crm/templates/user/user_detail.jinja2
{% extends "base.jinja2" %}
{% block content %}
<h1>
    <strong>{{ user.Name }}</strong>님의 상세정보
</h1>
<div class="card border-success my-3">
    <div class="card-header">기본정보 (UUID: {{ user.Id }})</div>
    <div class="card-body">
        <dl class="row my-2">
            <dt class="col-sm-1">이름</dt>
            <dd class="col-sm-11">
                {{ user.Name }}
            </dd>
            <dt class="col-sm-1">성별</dt>
            <dd class="col-sm-11">
                {{ user.Gender }}
            </dd>
            <dt class="col-sm-1">나이</dt>
            <dd class="col-sm-11">
                {{ user.Age }}
            </dd>
            <dt class="col-sm-1">생일</dt>
            <dd class="col-sm-11">
                {{ user.Birthday|date }}
            </dd>
            <dt class="col-sm-1">주소</dt>
            <dd class="col-sm-11">
                {{ user.Address }}
            </dd>
        </dl>
    </div>
</div>
<div class="card border-primary my-3">
    <div class="card-header">
        주문내역 (총 <strong>{{ order_list|count }}</strong>건)
    </div>
    <ul class="list-group list-group-flush">
        {% for store in order_list %}
        <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-start"
            aria-current="true">
            <div class="ms-2 me-auto">
                <a href="{{ url_for('store.get_store', id=store.Store.Id) }}"
                    class="text-primary text-decoration-none"><strong>{{ store.Name }}</strong> - {{ store.Type
                    }}</a>
            </div>
            <div><a href="/" class="text-primary text-decoration-none">{{ store.OrderAt|datetime }}</a></div>
        </li>
        {% endfor %}
    </ul>
</div>
<div class="card border-warning my-3">
    <div class="card-header">자주 방문한 매장 TOP 5</div>
    <ul class="list-group list-group-flush">
        {% for top in store_top5 %}
        <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-start"
            aria-current="true">
            <div class="ms-2 me-auto">
                <a href="{{ url_for('store.get_store', id=top.Store.Id) }}"
                    class="text-primary text-decoration-none"><strong>{{ top.Name }}</strong> - {{ top.Type
                    }}</a>
            </div>
            <span>{{ top.visit_count }}회 방문</span>
        </li>
        {% endfor %}
    </ul>
</div>
<div class="card border-warning my-3">
    <div class="card-header">자주 주문한 상품 TOP 5</div>
    <ul class="list-group list-group-flush">
        {% for top in item_top5 %}
        <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-start"
            aria-current="true">
            <div class="ms-2 me-auto">
                <a href="{{ url_for('item.get_item', id=top.Item.Id) }}"
                    class="text-primary text-decoration-none"><strong>{{ top.Name }}</strong> - {{ top.Type
                    }}</a>
            </div>
            <span>{{ top.order_count }}회 주문</span>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

crm/templates/user/user_list.jinja2
{% extends "base.jinja2" %}
{% block content %}
<h1>전체 회원 리스트</h1>
<hr />
<form action='{{ url_for("user.get_users") }}' class="row g-3 justify-content-center">
    <div class="col-4">
        <input type="text" class="form-control" id="name" name="name" placeholder="{{ name or '이름' }}" />
    </div>
    <div class="col-4">
        <input type="number" class="form-control" id="age" name="age" placeholder="{{ age or '나이' }}" />
    </div>
    <div class="col-2">
        <select id="gender" name="gender" class="form-select">
            <option selected hidden value="{{ gender or '' }}">{{ gender or '성별' }}</option>
            <option value="">전체</option>
            <option>남</option>
            <option>여</option>
        </select>
    </div>
    <div class="col-auto text-center">
        <button type="submit" class="btn btn-primary px-3">검색</button>
    </div>
    <div class="col-auto text-center">
        <a href="{{ url_for('user.get_users') }}" class="btn btn-danger px-3">초기화</a>
    </div>
</form>
<hr />
<div class="card my-3">
    <div class="card-header">총 회원: {{ '{:,}'.format(user_total) }}명</div>
    <ul class="list-group list-group-flush">
        {% for users in user_list %}
        <a href="{{ url_for('user.get_user', id=users.Id) }}"
            class="list-group-item list-group-item-action d-flex justify-content-between align-items-start"
            aria-current="true">
            <div class="ms-2 me-auto">
                <div class="fw-bold">
                    {{ users.Name }}
                    {% if users.Gender == "남" %}
                    <span class="badge bg-primary ms-1">{{ users.Gender }} ({{ users.Age }})</span>
                    {% else %}
                    <span class="badge bg-danger ms-1">{{ users.Gender }} ({{ users.Age }})</span>
                    {% endif %}
                </div>
            </div>
            <span>{{ users.Address }}</span>
        </a>
        {% endfor %}
    </ul>
</div>
<!-- 페이징처리 시작 -->
<ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if user_list.has_prev %}
    <li class="page-item">
        <a class="page-link"
            href="?page={{ user_list.prev_num }}&name={{ name or '' }}&gender={{ gender or '' }}&age={{ age or '' }}"><i
                class="bi bi-caret-left-fill"></i></a>
    </li>
    {% endif %}
    <!-- 페이지번호 -->
    {% for page_num in user_list.iter_pages() %}
    {% if page_num %}
    {% if
    page_num == user_list.page %}
    <li class="page-item active" aria-current="page">
        <a class="page-link" href="#">{{ page_num }}</a>
    </li>
    {% elif page_num == 1 or page_num == user_list.pages or (page_num >=
    user_list.page - 2 and page_num <= user_list.page + 2) %} <li class="page-item">
        <a class="page-link"
            href="?page={{ page_num }}&name={{ name or '' }}&gender={{ gender or '' }}&age={{ age or '' }}">{{ page_num
            }}</a>
        </li>
        {% elif (page_num == user_list.page - 3 and user_list.page > 3) or (page_num
        == user_list.page + 3 and user_list.page < user_list.pages - 3) %} <li class="disabled">
            <a class="page-link" href="#">...</a>
            </li>
            {% endif %}
            {% else %}
            <li class="disabled">
                <a class="page-link" href="#">...</a>
            </li>
            {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if user_list.has_next %}
            <li class="page-item">
                <a class="page-link"
                    href="?page={{ user_list.next_num }}&name={{ name or '' }}&gender={{ gender or '' }}&age={{ age or '' }}"><i
                        class="bi bi-caret-right-fill"></i></a>
            </li>
            {% endif %}
</ul>
<!-- 페이징처리 끝 -->
{% endblock content %}