crm/views/item.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from sqlalchemy import func
from crm.models import User, Order, Store, Item, OrderItem

bp = Blueprint("item", __name__, url_prefix="/item")


@bp.route("/")
def get_items():
    page = request.args.get("page", 1, type=int)
    per_page = request.args.get("per_page", 10, type=int)

    if page < 1 or per_page * (page - 1) > Item.query.count():
        flash("페이지 번호가 잘못되었습니다. 첫 페이지로 이동합니다.", "danger")
        page = 1

    item_list = Item.query.paginate(page=page, per_page=per_page)
    item_total = Item.query.count()

    name = request.args.get("name")

    if name:
        item_list = Item.query.filter(Item.Name.like(f"%{name}%")).paginate(
            page=page, per_page=per_page
        )
        item_total = Item.query.filter(Item.Name.like(f"%{name}%")).count()

        if item_total == 0:
            flash("해당 이름의 상품이 존재하지 않습니다.", "danger")
            return redirect(url_for("item.get_items"))

    return render_template(
        "item/item_list.jinja2",
        title="전체 상품 목록",
        item_list=item_list,
        item_total=item_total,
        name=name,
    )


@bp.route("/<id>")
def get_item(id):
    try:
        item = Item.query.get(id)

        if not item:
            flash("해당 상품이 존재하지 않습니다.", "danger")
            return redirect(url_for("item.get_items"))

        # ! 월간 매출액 가져오기
        # ? 1. Order 테이블과 OrderItem 테이블을 조인하여 Item 테이블의 UnitPrice를 가져온다.
        # ? 2. Order 테이블의 OrderAt 컬럼을 기준으로 월간 매출액과 주문수 리스트를 가져온다.

        sales = (
            Order.query.join(OrderItem, Order.Id == OrderItem.OrderId)
            .join(Item, OrderItem.ItemId == Item.Id)
            .add_columns(
                func.strftime("%Y년 %m월", Order.OrderAt).label("Month"),
                func.sum(Item.UnitPrice).label("MonthlySales"),
                func.count(OrderItem.Id).label("OrderCount"),
            )
            .filter(OrderItem.ItemId == id)
            .group_by("Month")
            .order_by(Order.OrderAt.desc())
            .all()
        )

        # 월간 매출액 그래프
        chart_month = []
        for sale in sales:
            chart_month.append(sale.Month)

        chart_sales = []
        for sale in sales:
            chart_sales.append(sale.MonthlySales)

        chart_sales_count = []
        for sale in sales:
            chart_sales_count.append(sale.OrderCount)

        return render_template(
            "item/item_detail.jinja2",
            title="상품 상세 정보",
            item=item,
            sales=sales,
            chart_month=chart_month,
            chart_sales=chart_sales,
            chart_sales_count=chart_sales_count,
        )
    except:
        flash("상품 정보를 가져오는 중 오류가 발생했습니다.", "danger")
        return redirect(url_for("item.get_items"))

crm/views/order.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from sqlalchemy import func
from crm.models import User, Order, Store, Item, OrderItem

bp = Blueprint("order", __name__, url_prefix="/order")


@bp.route("/")
def get_orders():
    page = request.args.get("page", 1, type=int)
    per_page = request.args.get("per_page", 10, type=int)

    if page < 1 or per_page * (page - 1) > Order.query.count():
        flash("페이지 번호가 잘못되었습니다. 첫 페이지로 이동합니다.", "danger")
        page = 1

    order_list = Order.query.order_by(Order.OrderAt.desc()).paginate(
        page=page, per_page=per_page
    )
    order_total = Order.query.count()

    # ? 이게 왜 되는거지? ㅡ..ㅡ; 스스로에게 값을 추가?
    for order in order_list.items:
        user = User.query.get(order.UserId)
        store = Store.query.get(order.StoreId)
        order.UserName = user.Name
        order.StoreName = store.Name
        order.StoreType = store.Type

    return render_template(
        "order/order_list.jinja2",
        title="전체 주문 목록",
        order_list=order_list,
        order_total=order_total,
    )


@bp.route("/<id>")
def get_order(id):
    try:
        order = Order.query.get(id)

        if not order:
            flash("해당 주문이 존재하지 않습니다.", "danger")
            return redirect(url_for("order.get_orders"))

        # ! 해당 id에 대한 주문 상세 정보 가져오기
        order_detail = (
            Order.query.join(OrderItem, Order.Id == OrderItem.OrderId)
            .join(Item, OrderItem.ItemId == Item.Id)
            .add_columns(Item.Id, Item.Name, Item.UnitPrice)
            .filter(Order.Id == id)
            .all()
        )

        store = Store.query.get(order.StoreId)
        user = User.query.get(order.UserId)

        total_price = sum([item.UnitPrice for item in order_detail])

        print(total_price)

        return render_template(
            "order/order_detail.jinja2",
            title="주문 상세 정보",
            order=order,
            order_detail=order_detail,
            store=store,
            user=user,
            total_price=total_price,
        )
    except:
        flash("해당 주문이 존재하지 않습니다.", "danger")
        return redirect(url_for("order.get_orders"))

crm/views/user.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from sqlalchemy import func
from crm.models import User, Order, Store, Item, OrderItem

bp = Blueprint("user", __name__, url_prefix="/user")


@bp.route("/")
def get_users():
    page = request.args.get("page", 1, type=int)
    per_page = request.args.get("per_page", 10, type=int)

    if page < 1 or per_page * (page - 1) > User.query.count():
        flash("페이지 번호가 잘못되었습니다. 첫 페이지로 이동합니다.", "danger")
        page = 1

    name = request.args.get("name")
    gender = request.args.get("gender")
    age = request.args.get("age")

    user_list = User.query.paginate(page=page, per_page=per_page)
    user_total = User.query.count()

    if name:
        user_list = User.query.filter(User.Name.like(f"%{name}%")).paginate(
            page=page, per_page=per_page
        )
        user_total = User.query.filter(User.Name.like(f"%{name}%")).count()
        if user_total == 0:
            flash("해당 이름의 회원이 존재하지 않습니다.", "danger")
            return redirect(url_for("user.get_users"))

    if gender:
        user_list = User.query.filter(User.Gender == gender).paginate(
            page=page, per_page=per_page
        )
        user_total = User.query.filter(User.Gender == gender).count()
        if user_total == 0:
            flash("해당 성별의 회원이 존재하지 않습니다.", "danger")
            return redirect(url_for("user.get_users"))

    if age:
        user_list = User.query.filter(User.Age == age).paginate(
            page=page, per_page=per_page
        )
        user_total = User.query.filter(User.Age == age).count()
        if user_total == 0:
            flash("해당 나이의 회원이 존재하지 않습니다.", "danger")
            return redirect(url_for("user.get_users"))

    return render_template(
        "user/user_list.jinja2",
        title="전체 회원 목록",
        user_list=user_list,
        user_total=user_total,
        name=name,
        gender=gender,
        age=age,
    )


@bp.route("/<id>")
def get_user(id):
    try:
        user = User.query.get(id)

        if not user:
            flash("해당 회원이 존재하지 않습니다.", "danger")
            return redirect(url_for("user.get_users"))

        # 주문 내역

        order_list = (
            Store.query.join(Order, Store.Id == Order.StoreId)
            .add_columns(Store.Name, Store.Type, Order.OrderAt)
            .filter(Order.UserId == id)
            .order_by(Order.OrderAt.desc())
            .all()
        )

        # store_top5 = (
        #     Store.query.join(Order, Store.Id == Order.StoreId)
        #     .add_columns(Store.Name, Store.Type)
        #     .filter(Order.UserId == id)
        #     .group_by(Store.Id)
        #     .order_by(func.count().desc())
        #     .limit(5)
        # )

        # visited_count = (
        #     Order.query.filter(Order.UserId == id)
        #     .add_columns(Order.StoreId, func.count())
        #     .group_by(Order.StoreId)
        #     .order_by(func.count().desc())
        #     .all()
        # )

        # 자주 방문한 매장 TOP5

        store_top5_visit = (
            Store.query.join(Order, Store.Id == Order.StoreId)
            .filter(Order.UserId == id)
            .add_columns(
                Store.Name, Store.Type, func.count(Order.StoreId).label("visit_count")
            )
            .group_by(Store.Id)
            .order_by(func.count(Order.StoreId).desc())
            .limit(5)
            .all()
        )

        # 자주 주문한 상품 TOP5

        item_top5 = (
            Item.query.join(OrderItem, Item.Id == OrderItem.ItemId)
            .join(Order, Order.Id == OrderItem.OrderId)
            .filter(Order.UserId == id)
            .add_columns(
                Item.Name, Item.Type, func.count(OrderItem.ItemId).label("order_count")
            )
            .group_by(Item.Id)
            .order_by(func.count(OrderItem.ItemId).desc())
            .limit(5)
            .all()
        )

        return render_template(
            "user/user_detail.jinja2",
            title=f"{user.Name}님의 회원 정보",
            user=user,
            order_list=order_list,
            store_top5=store_top5_visit,
            item_top5=item_top5,
        )
    except:
        flash("사용자 정보를 가져오는 중 오류가 발생했습니다.", "danger")
        return redirect(url_for("user.get_users"))

crm/templates/order/order_detail.jinja2
{% extends 'base.jinja2' %}
{% block content %}
<h1>
    <strong>{{ order.OrderAt|date }}</strong> 주문 상세내역
</h1>
<hr>
<div class="card border-success my-3">
    <div class="card-header">기본정보 (UUID: {{ order.Id }})</div>
    <div class="card-body">
        <dl class="row my-2">
            <dt class="col-sm-2">주문시간</dt>
            <dd class="col-sm-10">
                {{ order.OrderAt|datetime }}
            </dd>
            <dt class="col-sm-2">매장명</dt>
            <dd class="col-sm-10">
                {{ store.Name }}
            </dd>
            <dt class="col-sm-2">지점명</dt>
            <dd class="col-sm-10">
                {{ store.Type }}
            </dd>
            <dt class="col-sm-2">주문자 명</dt>
            <dd class="col-sm-10">
                <a href="{{ url_for('user.get_user', id=user.Id) }}" class="text-decoration-none text-primary">{{
                    user.Name }}</a>
            </dd>
            <dt class="col-sm-2">총 주문금액</dt>
            <dd class="col-sm-10">
                ₩ {{ '{:,}'.format(total_price) }}
            </dd>
        </dl>
    </div>
</div>
<div class="card border-primary my-3">
    <div class="card-header">
        상세 내역
    </div>
    <ul class="list-group list-group-flush">
        {% for item in order_detail %}
        <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-start">
            <div class="ms-2 me-auto">
                <span class="fw-bold"><a href="{{ url_for('item.get_item', id=item.Id) }}"
                        class="text-decoration-none text-primary">{{ item.Name }}</a></span>
            </div>
            <div>₩ {{ '{:,}'.format(item.UnitPrice) }}</div>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

crm/templates/order/order_list.jinja2
{% extends 'base.jinja2' %}
{% block content %}
<h1>전체 주문 내역</h1>
<hr>
<div class="card my-3">
    <div class="card-header">총 주문: {{ '{:,}'.format(order_total) }}개</div>
    <ul class="list-group list-group-flush">
        {% for orders in order_list %}
        <a href="{{ url_for('order.get_order', id=orders.Id) }}"
            class="list-group-item list-group-item-action d-flex justify-content-between align-items-start"
            aria-current="true">
            <div class="ms-2 me-auto">
                <div>
                    [ <span class="text-primary fw-bold">{{ orders.StoreName }}</span> ] {{ orders.StoreType }}
                </div>
            </div>
            <span>{{ orders.OrderAt|datetime }}</span>
        </a>
        {% endfor %}
    </ul>
</div>
<!-- 페이징처리 시작 -->
<ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if order_list.has_prev %}
    <li class="page-item">
        <a class="page-link" href="?page={{ order_list.prev_num }}"><i class="bi bi-caret-left-fill"></i></a>
    </li>
    {% endif %}
    <!-- 페이지번호 -->
    {% for page_num in order_list.iter_pages() %}
    {% if page_num %}
    {% if page_num == order_list.page %}
    <li class="page-item active" aria-current="page">
        <a class="page-link" href="#">{{ page_num }}</a>
    </li>
    {% elif page_num == 1 or page_num == order_list.pages or (page_num >= order_list.page - 2 and page_num <=
        order_list.page + 2) %} <li class="page-item">
        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% elif (page_num == order_list.page - 3 and order_list.page > 3) or (page_num == order_list.page + 3 and
        order_list.page < order_list.pages - 3) %} <li class="disabled">
            <a class="page-link" href="#">...</a>
            </li>
            {% endif %}
            {% else %}
            <li class="disabled">
                <a class="page-link" href="#">...</a>
            </li>
            {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if order_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ order_list.next_num }}"><i class="bi bi-caret-right-fill"></i></a>
            </li>
            {% endif %}
</ul>
<!-- 페이징처리 끝 -->
{% endblock %}